type: "BonnPBRLatentBRDF"
module: "models.neural_brdf_refactored"
data_folder: ${dataset_folder}
debug: ${data.debug}
debug_num: ${data.debug_num}
debug_rotate: ${data.debug_rotate}
debug_swap_channels: ${data.debug_swap_channels}
predict_frame: True
init_normal_from_gt: False
learnable_factor: False
init_std: 0.1

single_material_id: ${data.overfit_mat_id}
optimizer:
  name: ${model.optimizer.name}

anisotropic: True
disney: True
soft_constraint: True
