#!/bin/bash
# ---------------------------------------------------------------------------
# Stage 1 — BRDF-prior training on the Bonn UBOFAB19 SVBRDF dataset
# (the "Bonn" decoder column of the comparison tables).
#
# Path-configurable version of scripts/jobs/run_stage1_bonn_cc.sh (the exact
# paper configuration). See full_experiments.md §2 for how to download and
# preprocess the Bonn training data.
#
# Usage:
#   DATA_ROOT=/path/to/Bonn_train [OUTPUT_ROOT=...] bash train_stage1_bonn.sh
#
# Required under DATA_ROOT: mat####_{poly,pan,lls}.exr, mat####_xyz_rot000.exr,
#   mat####_calibration.mat, the svfresnel .axf files, and
#   bonn_point_metadata.json (generated by scripts/generate_bonn_metadata.py).
#
# Output: $OUTPUT_ROOT/$EXP_NAME/training/model_0.20_0.20/last.ckpt
#         (the released checkpoint of this run is checkpoints/stage1/Bonn.ckpt)
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/../../training"

DATA_ROOT=${DATA_ROOT:?set DATA_ROOT to the Bonn_train folder}
OUTPUT_ROOT=${OUTPUT_ROOT:-$PWD/outputs/full_experiments}
EXP_NAME=${EXP_NAME:-Stage1_Bonn_run_1}
MAX_EPOCHS=${MAX_EPOCHS:-100}
RAYS_NUM=${RAYS_NUM:-500000}
export WANDB_MODE=${WANDB_MODE:-offline}

python train.py \
    dataset_folder="$DATA_ROOT" \
    output_folder="$OUTPUT_ROOT" \
    exp_output_root_path="$OUTPUT_ROOT/$EXP_NAME" \
    data=bonn \
    data.num_load_workers=2 \
    data.use_pan=True \
    data.use_lls=True \
    data.debug=False \
    data.debug_num=200 \
    data.rays_num=$RAYS_NUM \
    data.point_subsample_ratio=0.1 \
    renderer=multiarea_emitter \
    material=bonn_latent \
    experiment_name="$EXP_NAME" \
    model.optimizer.reset_latent_momentum_on_chunk_switch=False \
    model.optimizer.name=Adam8bit \
    model.loss.recon_loss.name=logrel \
    model.loss.recon_loss.log_space.logrel_ref=0.02 \
    model.loss.reg_loss.weight=0.0 \
    model.loss.pan_weight=1.0 \
    model.loss.lls_weight=1.0 \
    model.psnr.global_psnr=False \
    model.lls_spp=4 \
    model.stage=1 \
    model.test=False \
    model.apply_cosine_weight=True \
    model.continue_training=False \
    model.trainer.max_epochs=$MAX_EPOCHS \
    model.optimizer.lr=2e-3 \
    model.optimizer.decoder_lr=2e-4 \
    model.trainer.limit_train_batches=8000 \
    model.trainer.check_val_every_n_epoch=5 \
    model.grazing_ratio=0.05 \
    model.grazing_mode=contribution_decay \
    material.decoder.use_skip_connection=True \
    material.decoder.use_film=False \
    material.decoder.use_color_decomp=False \
    material.latent_dim=24 \
    material.decoder.degree=3 \
    material.decoder.smooth_reg=False \
    material.different_decoder=False \
    data.filter_observations=False \
    "$@"
