# @package _global_
# UBOPBRLatentBRDF (Disney) trained on real measurements (apply_cosine_weight=True).
renderer_name: pbr
material_type: UBOPBRLatentBRDF
use_btf: false
btf_path: /media/raid/cloth/BTF/${material_id}_W400xH400_L151xV151.btf
ckpt_path: /media/raid/cloth/output/BRDF/BTF/Bonn-Theia2/Stage-2_PBR-Disney_UBO_${material_id}_Cosine_run_1/training/model_0.20_0.20/last.ckpt
apply_cosine_at_eval: true
