defaults:
  - data: points_dense
  - renderer: realcapture_area_emitter
  - model: base
  - material: multi_material_latent

experiment_name: test
# exp_folder: /media/raid/cloth/No_cable_capture_Sep22/BRDF_recon_Sep30/Controlled_light/hdr
dataset_folder: /home/featurize/data
output_folder: /media/raid/cloth/output/BRDF
exp_output_root_path: ${output_folder}/${experiment_name}
gt_folder: ${dataset_folder}/hdr
test_on_train: True
global_train_seed: 42
